import * as XLSX from 'xlsx';

// Force Node.js runtime (not Edge)
export const runtime = 'nodejs';

// ─── Finance math (mirrors DealDetail.jsx runModel exactly) ──────────────────

function parseNum(val) {
  if (typeof val === 'number') return val;
  return parseFloat(String(val).replace(/[$,]/g, '').trim()) || 0;
}

function approxIRR(cfs, lo = -0.5, hi = 5.0) {
  for (let i = 0; i < 120; i++) {
    const mid = (lo + hi) / 2;
    const npv = cfs.reduce((s, cf, t) => s + cf / Math.pow(1 + mid, t), 0);
    if (Math.abs(npv) < 0.01) return mid;
    npv > 0 ? (lo = mid) : (hi = mid);
  }
  return (lo + hi) / 2;
}

function calcModel(inputs) {
  const price   = parseNum(inputs.price);
  const rent    = parseNum(inputs.rent);
  const sf      = parseNum(inputs.sf);
  const exitCap = parseNum(inputs.exitCap) / 100;
  const ltv     = parseNum(inputs.ltv)     / 100;
  const rate    = parseNum(inputs.rate)    / 100;
  const bumps   = parseNum(inputs.bumps)   / 100;
  const hold    = Math.max(1, parseInt(inputs.hold) || 5);
  const mktRent = parseNum(inputs.marketRent);

  const noi0    = rent * sf * 12;
  const goingIn = price > 0 ? noi0 / price : 0;
  const noiArr  = Array.from({ length: hold }, (_, y) => noi0 * Math.pow(1 + bumps, y));

  const loan   = price * ltv;
  const equity = price * (1 - ltv);
  const moRate = rate / 12;
  const moPmt  = rate > 0 ? loan * moRate / (1 - Math.pow(1 + moRate, -360)) : 0;
  const ds     = moPmt * 12;
  const dscr   = ds > 0 ? noiArr[0] / ds : 0;

  const exitNOI = noi0 * Math.pow(1 + bumps, hold);
  const exitVal = exitCap > 0 ? exitNOI / exitCap : 0;

  const cfUnlev = [-price, ...noiArr.slice(0, -1), noiArr[hold - 1] + exitVal];
  const cfLev   = [
    -(price - loan),
    ...noiArr.slice(0, -1).map(n => n - ds),
    noiArr[hold - 1] - ds + exitVal - loan,
  ];

  const unlevirr = approxIRR(cfUnlev);
  const levirr   = approxIRR(cfLev);
  const em       = equity > 0
    ? (cfLev.slice(1).reduce((a, b) => a + b, 0) + equity) / equity
    : 0;

  return {
    price, rent, sf, exitCap, ltv, rate, bumps, hold, mktRent,
    noi0, goingIn, noiArr, loan, equity, ds, dscr,
    exitNOI, exitVal, cfUnlev, cfLev, unlevirr, levirr, em,
  };
}

// ─── Format helpers ───────────────────────────────────────────────────────────

const pct  = v => `${(v * 100).toFixed(2)}%`;
const pct1 = v => `${(v * 100).toFixed(1)}%`;
const usd  = v => `$${Math.round(v).toLocaleString()}`;
const mult = v => `${v.toFixed(2)}×`;

// ─── Workbook builder ─────────────────────────────────────────────────────────

function buildWorkbook(inputs, r) {
  const wb   = XLSX.utils.book_new();
  const name = inputs.dealName ?? 'Deal';
  const addr = inputs.address  ?? '';
  const head = addr ? `${name} — ${addr}` : name;

  // ── helpers ────────────────────────────────────────────────────────────────
  // aoa_to_sheet with column widths + optional freeze
  function makeSheet(aoa, colWidths, freeze) {
    const ws = XLSX.utils.aoa_to_sheet(aoa);
    if (colWidths) ws['!cols'] = colWidths.map(w => ({ wch: w }));
    if (freeze)    ws['!freeze'] = freeze;
    return ws;
  }

  // ── Sheet 1: Returns Summary ───────────────────────────────────────────────
  const irrStatus = v =>
    v > 0.16 ? 'Strong ✓' : v > 0.12 ? 'Meets hurdle ✓' : 'Below hurdle ⚠';
  const emStatus  = v =>
    v > 1.5  ? 'Strong ✓' : v > 1.2  ? 'OK ✓'           : 'Low ⚠';
  const dscrStat  = v =>
    v > 1.20 ? 'Meets min ✓' : 'Below min ✗';

  const s1 = makeSheet([
    ['CLERESTORY — Underwriting Model'],
    [head],
    [`${r.hold}-Year Hold  ·  Generated by Clerestory`],
    [],
    ['Metric',             'Value',             'Benchmark',          'Status',           'Notes'],
    ['Going-In Cap Rate',  pct(r.goingIn),      'Market: 5.0–5.5%',  '—',                'Initial yield on purchase price'],
    ['Unlevered IRR',      pct1(r.unlevirr),    'Hurdle: 10%',       irrStatus(r.unlevirr), 'Before leverage'],
    ['Levered IRR',        pct1(r.levirr),      'Hurdle: 12–16%',    irrStatus(r.levirr),   'After debt service'],
    ['Equity Multiple',    mult(r.em),           'Target: >1.5×',     emStatus(r.em),     'Total distributions / equity invested'],
    ['DSCR Year 1',        r.dscr.toFixed(2) + '×', 'Min: 1.20×',   dscrStat(r.dscr),   'Net Operating Income / Annual Debt Service'],
    ['Exit Cap Rate',      pct(r.exitCap),      'Assumption',        '—',                'Applied to terminal-year NOI'],
    ['Annual Rent Bumps',  pct1(r.bumps),       'Assumption',        '—',                'Compounding annual escalation'],
    [],
    ['Going-In Cap',       pct(r.goingIn)],
    ['Unlevered IRR',      pct1(r.unlevirr)],
    ['Levered IRR',        pct1(r.levirr)],
    ['Equity Multiple',    mult(r.em)],
    ['DSCR Yr 1',          r.dscr.toFixed(2) + '×'],
  ], [26, 16, 22, 20, 38]);
  XLSX.utils.book_append_sheet(wb, s1, 'Returns Summary');

  // ── Sheet 2: Inputs ────────────────────────────────────────────────────────
  const s2 = makeSheet([
    ['DEAL INPUTS',        '',              head],
    [],
    ['— Deal Parameters —'],
    ['Purchase Price',     r.price,         '', '$/SF', r.sf > 0 ? +(r.price / r.sf).toFixed(0) : ''],
    ['Building SF',        r.sf],
    ['In-Place Rent',      r.rent,          '$/SF/Mo NNN'],
    ['Market Rent',        r.mktRent,       '$/SF/Mo NNN'],
    ['Hold Period',        r.hold,          'Years'],
    [],
    ['— Assumptions —'],
    ['Exit Cap Rate',      r.exitCap,       '', 'format', pct(r.exitCap)],
    ['Annual Rent Bumps',  r.bumps,         '', 'format', pct1(r.bumps)],
    ['LTV',                r.ltv,           '', 'format', pct(r.ltv)],
    ['Interest Rate',      r.rate,          '', 'format', pct(r.rate)],
    [],
    ['— Derived Values —'],
    ['Year 1 NOI',         r.noi0,          '', 'format', usd(r.noi0)],
    ['Loan Amount',        r.loan,          '', 'format', usd(r.loan)],
    ['Equity Required',    r.equity,        '', 'format', usd(r.equity)],
    ['Annual Debt Service',r.ds,            '', 'format', usd(r.ds)],
    ['Going-In Cap Rate',  r.goingIn,       '', 'format', pct(r.goingIn)],
    ['Exit NOI',           r.exitNOI,       '', 'format', usd(r.exitNOI)],
    ['Exit Value',         r.exitVal,       '', 'format', usd(r.exitVal)],
  ], [28, 18, 18, 10, 16]);

  // Apply number formats to column B of the derived rows
  ['D4','D5','D6','D7','D8'].forEach(ref => {
    if (s2[ref]) s2[ref].z = '#,##0.00';
  });
  // Price/SF formula-style
  ['B4','B5','B6','B7'].forEach(ref => {
    if (s2[ref]) s2[ref].z = '#,##0.00';
  });
  XLSX.utils.book_append_sheet(wb, s2, 'Inputs');

  // ── Sheet 3: Cash Flows ────────────────────────────────────────────────────
  const yrHeaders = ['Year 1', ...Array.from({ length: r.hold - 1 }, (_, i) => `Year ${i + 2}`)];
  const total = arr => arr.reduce((a, b) => a + (b ?? 0), 0);

  const cfRows = [
    ['CASH FLOW MODEL', '', head],
    [],
    ['',           'Acquisition', ...yrHeaders, 'Total'],
    // Unlevered
    ['— Unlevered'],
    ['NOI',                  '',      ...r.noiArr,                                   total(r.noiArr)],
    ['Exit Value',           '',      ...Array(r.hold - 1).fill(''), r.exitVal,      r.exitVal],
    ['Total Unlevered CF',   r.cfUnlev[0], ...r.cfUnlev.slice(1),               total(r.cfUnlev)],
    [],
    // Levered
    ['— Levered'],
    ['Loan Proceeds',        r.loan,  ...Array(r.hold).fill('')],
    ['Annual Debt Service',  '',      ...Array(r.hold).fill(-r.ds),              -r.ds * r.hold],
    ['Loan Repayment',       '',      ...Array(r.hold - 1).fill(''), -r.loan,    -r.loan],
    ['Total Levered CF',     r.cfLev[0], ...r.cfLev.slice(1),                   total(r.cfLev)],
  ];

  const s3 = makeSheet(cfRows, [
    24, 14, ...Array(r.hold).fill(12), 14,
  ], { xSplit: 1, ySplit: 2, topLeftCell: 'B3' });

  // Apply currency format to all numeric cells in the CF sheet
  const cfRef = s3['!ref'];
  if (cfRef) {
    const range = XLSX.utils.decode_range(cfRef);
    for (let row = range.s.r; row <= range.e.r; row++) {
      for (let col = range.s.c + 1; col <= range.e.c; col++) {
        const addr2 = XLSX.utils.encode_cell({ r: row, c: col });
        if (s3[addr2] && s3[addr2].t === 'n') {
          s3[addr2].z = '$#,##0';
        }
      }
    }
  }
  XLSX.utils.book_append_sheet(wb, s3, 'Cash Flows');

  // ── Sheet 4: Sensitivity ───────────────────────────────────────────────────
  const exitCaps    = [4.50, 4.75, 5.00, 5.25, 5.50, 5.75];
  const rentGrowths = [2.0, 2.5, 3.0, 3.5, 4.0];

  const sensRows = [
    ['IRR SENSITIVITY — Levered IRR', '', head],
    ['Exit Cap Rate vs. Annual Rent Growth  ·  Base case: 5.25% cap, 3.0% bumps'],
    [],
    ['Exit Cap \\ Rent Growth', ...rentGrowths.map(rg => `${rg.toFixed(1)}%`)],
  ];

  for (const cap of exitCaps) {
    const row = [`${cap.toFixed(2)}%`];
    for (const rg of rentGrowths) {
      const res = calcModel({ ...inputs, exitCap: String(cap), bumps: String(rg) });
      const isBase = Math.abs(cap - 5.25) < 0.01 && Math.abs(rg - 3.0) < 0.01;
      // Mark base case with asterisk
      row.push(isBase ? `${pct1(res.levirr)} *` : pct1(res.levirr));
    }
    sensRows.push(row);
  }

  sensRows.push([]);
  sensRows.push(['* Base case (5.25% exit cap, 3.0% rent growth)']);
  sensRows.push(['IRR > 16% = Strong   ·   12–16% = Meets Hurdle   ·   < 12% = Below Hurdle']);

  const s4 = makeSheet(sensRows, [24, ...rentGrowths.map(() => 12)]);
  XLSX.utils.book_append_sheet(wb, s4, 'Sensitivity');

  return wb;
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(request) {
  try {
    const inputs = await request.json();

    const r  = calcModel(inputs);
    const wb = buildWorkbook(inputs, r);

    // Write to buffer — no temp files, no filesystem, no Python
    const buf = XLSX.write(wb, { bookType: 'xlsx', type: 'buffer' });

    const raw      = (inputs.dealName ?? 'UW_Model').replace(/[^\w\s-]/g, '').trim();
    const slug     = raw.replace(/\s+/g, '_') || 'UW_Model';
    const dateStr  = new Date().toISOString().slice(0, 10);
    const filename = `Clerestory_UW_${slug}_${dateStr}.xlsx`;

    return new Response(buf, {
      status: 200,
      headers: {
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(buf.length),
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    console.error('[export-model]', err);
    return Response.json(
      { error: 'Export failed: ' + (err?.message ?? 'Unknown error') },
      { status: 500 },
    );
  }
}
